---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yaml

  tasks:
    - name: Creating resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
        state: present
      register: creating_resource_group

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ virtual_network }}"
        state: present
        address_prefixes: "10.0.0.0/16"

    - name: Create subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ subnet_network }}"
        address_prefixes: "10.0.1.0/24"
        state: present
        virtual_network: "{{ virtual_network }}"

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: "{{ public_ip }}"
        state: present

    - name: Create network security group that allows SSH
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ security_group }}"
        state: present
        rules:
          - name: SSH
            access: Allow
            protocol: Tcp
            destination_port_range: 22
            priority: 120
            direction: Inbound

    - name: Create network security group that allows counter strike
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ security_group }}"
        state: present
        rules:
          - name: counter_strike_27015_tcp
            access: Allow
            protocol: Tcp
            destination_port_range: 27015
            priority: 121
            direction: Inbound
          - name: counter_strike_27015_udp
            access: Allow
            protocol: Udp
            destination_port_range: 27015
            priority: 122
            direction: Inbound

    - name: Create virtual network interface card
      azure_rm_networkinterface:
        name: "{{ network_interface }}"
        resource_group: "{{ resource_group }}"
        virtual_network: "{{ virtual_network }}"
        subnet: "{{ subnet_network }}"
        public_ip_name: "{{ public_ip }}"
        security_group: "{{ security_group }}"
        state: present

    - name: Create virutal machine
      azure_rm_virtualmachine:
        name: "{{ virtual_machine_01 }}"
        resource_group: "{{ resource_group }}"
        vm_size: "{{ virtual_machine_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        network_interface: "{{ network_interface }}"
        image:
          offer: debian-10
          publisher: Debian
          sku: 10
          version: latest
