---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yaml
  tasks:
    - name: Deleting resource group - "{{ resource_group }}"
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        force_delete_nonempty: yes
        state: absent
      register: deleting_resource_group