- hosts: localhost
  connection: local
  vars_files:
    - vars.yaml
  tasks:
    - name: Deleting resource group - "{{ resource_group }}"
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        state: absent

    - name: Deleting virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ virtual_network }}"
        state: absent

    - name: Create subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ subnet_network }}"
        virtual_network: "{{ virtual_network }}"
        state: absent