---
- hosts: azure
  vars_files:
    - vars.yaml

  tasks:
    - name: Download Script de Instalacao do Docker
      get_url:
        url: "{{ url_docker_script }}"
        dest: "{{ dst_docker_script }}"
        mode: "0755"
      register: download_script

    - name: Instalando o Docker
      command: "{{ dst_docker_script }}"
      when: download_script | default(false) | bool
      notify: Restart Docker
      register: instalando_docker

    - name: Removendo script de instalacao do Docker
      file:
        path: "{{ dst_docker_script }}"
        state: "absent"
      register: removendo_script